### ISSUE TITLE
When entering the gun store and backing up, you sometimes fall out of the map

### ISSUE THREAD

**Issue by DeathByKorea** [broke-protocol/BrokeProtocol#10]
Version 0.652

**Comment by DeathByKorea** [comment]
This may happen with all interiors

**Comment by BrokeProtocol** [comment]
Still problem in 0.72

**Comment by UserR00T** [comment]
When falling outside of interior more than around hundred feet or so, it'll reset you to the door's position. Thank you for reporting this issue!
