### ISSUE TITLE
Blood splatters can be seen through the void

### ISSUE THREAD

**Issue by Ternzeeh** [broke-protocol/BrokeProtocol#105]
Whenever a blood splatter is produced from the overworld (outside world of the game), the blood can be seen in the same location but in the void if you are inside a building.

![image](https://user-images.githubusercontent.com/29814492/28247372-75fe31fa-6a61-11e7-91ec-16ec4b14488b.png)

**Comment by BrokeProtocol** [comment]
Should be fixed in latest test version 10, need to confirm.

**Comment by BrokeProtocol** [comment]
Not fixed.

![bloodsplatter](https://user-images.githubusercontent.com/29849122/28335667-2ab901bc-6bcd-11e7-9aa2-fe6bab9be008.png)

**Comment by BrokeProtocol** [comment]
Still problem in 0.72

**Comment by UserR00T** [comment]
"this is by design.. keeping splatters and stuff on interiors can cause them to be destroyed if apartments are unloaded."
