### ISSUE TITLE
Server process hang

### ISSUE THREAD

**Issue by BrokeProtocol** [broke-protocol/BrokeProtocol#116]
Server will get removed from server list and you will not be able to connect to it, and the server process will remain and not close. Happens on Linux and Windows based servers. It seems to happen randomly, I've had it happen when server ran for 12hr+ or even less than 3hrs.

Might be due to something a player does on server, currently don't know how to reproduce.

Maybe auto close process if it cannot connect to master server list.

**Comment by BrokeProtocol** [comment]
Should've been closed long time ago.

**Comment by UserR00T** [comment]
Still a common thing that servers crash without a reason.

**Comment by UserR00T** [comment]
Most of the issues leading to a server crash have been fixed, and the server will try to reconnect to the masterserver when disconnected so theoretically should not occur again. Thank you for reporting this issiue!
