### ISSUE TITLE
Username ban

### ISSUE THREAD

**Issue by UserR00T** [broke-protocol/BrokeProtocol#187]
Hey, i am a mod on a server and have a problem, when you ban someone they just change their IP and join again. 

- Can you implement a Username ban? (if username is banned kick or something)

Thanks
-UserR00T

**Comment by BrokeProtocol** [comment]
Maybe when game comes to steam it will be able to ban their steamid instead. You can still bypass name bans easily.

**Comment by UserR00T** [comment]
SteamID support is coming very soon. Expect it in the next few months.
