### ISSUE TITLE
ATM disappears when clicking 'Join server'

### ISSUE THREAD

**Issue by UserR00T** [broke-protocol/BrokeProtocol#209]
The ATM disappears when clicking 'Join server'
Check the video, it explains itself.

Proof: [https://puu.sh/xeUSN/d89531c0ad.mp4](https://puu.sh/xeUSN/d89531c0ad.mp4)

**Comment by Ternzeeh** [comment]
sharp eyes you got there

**Comment by UserR00T** [comment]
hehe ;)

**Comment by UserR00T** [comment]
Old main menu camera position has been changed, issue not relevant anymore. Closing.
