### ISSUE TITLE
Buyable vehicles no lock bug

### ISSUE THREAD

**Issue by Ternzeeh** [broke-protocol/BrokeProtocol#223]
*Might be the same as Issue #220, for better explanation*

In a server, whenever you or a player buys any of the vehicles that is available (humvee,choppers), the lock option of that/those vehicles will be gone when the buyer leaves the server. Rejoining or restarting the server (Based on what I experienced) after buying the vehicle does not fix this bug meaning anyone can enter the vehicles without paying for money.

**Comment by Ternzeeh** [comment]
not sure if client or server type bug

**Comment by BrokeProtocol** [comment]
Still a problem in 0.72

**Comment by UserR00T** [comment]
Has been fixed, closing. Thank you for reporting this issue!
