### ISSUE TITLE
Town Hall stuck behind furniture

### ISSUE THREAD

**Issue by BrokeProtocol** [broke-protocol/BrokeProtocol#287]
Reported by Padams on Discord in screenshots channel.

 ![](https://cdn.discordapp.com/attachments/336187647938789376/387193902412595201/25.png)
 ![](https://cdn.discordapp.com/attachments/336187647938789376/387194183724564490/26.png)

**Comment by Vixonary** [comment]
You can crouch jump over the couch seat.

**Comment by BrokeProtocol** [comment]
Thanks Vixonary! Should however still adjust the furniture a bit to avoid confusion and hard ache if another player stumbles into that spot.

**Comment by UserR00T** [comment]
Issue has been fixed a while ago but hasn't been closed yet. Thank you for reporting this issue!
