### ISSUE TITLE
Stuck at the GunShop

### ISSUE THREAD

**Issue by LightVelox** [broke-protocol/BrokeProtocol#316]
you can easily get stuck at the gunshop if you jump into the targets, if you look down in the game you jump a little higher so it's easy to get stuck in places like take, the targets could be a bit taller

**Comment by Vixonary** [comment]
You used to be able to jump out, I think they decreased your jump height though.

**Comment by UserR00T** [comment]
Fixed next update. Thank you for reporting this issue!
