### ISSUE TITLE
Drivers don't take damage from outside hits

### ISSUE THREAD

**Issue by TheReaperG** [broke-protocol/BrokeProtocol#334]
You can't hit people inside the cars from outside, you can punch through them to hit the car though.

![screenshot_15](https://user-images.githubusercontent.com/30944091/34416169-37a027c6-ec2d-11e7-8a40-107cf707d08c.png)

**Comment by FreeSpy443** [comment]
This is actually a major bug since that kinda makes you godlike since of the no damage thing

**Comment by UserR00T** [comment]
Has been fixed, closing. Thank you for reporting this issue!
