### ISSUE TITLE
UI of votekick doesn't go away when the vote ended

### ISSUE THREAD

**Issue by NYANCATZXC** [broke-protocol/BrokeProtocol#377]
![28](https://user-images.githubusercontent.com/35097834/35931650-49e9e6c2-0c46-11e8-9e98-5058d6683d3d.png)
![29](https://user-images.githubusercontent.com/35097834/35931653-4aefc316-0c46-11e8-939f-dc896ed4fb12.png)

- After kicking someone the countdown timer stays at zero
- ~12 players online: 3 voted yes, not enough to kick the player
- When rejoining the ui goes away

**Comment by NYANCATZXC** [comment]
it stays on the server

**Comment by UserR00T** [comment]
Has been fixed, closing. Thank you for reporting this issue!
