### ISSUE TITLE
Kidnapping NPCs inside Buildings

### ISSUE THREAD

**Issue by TheReaperG** [broke-protocol/BrokeProtocol#390]
People should not be able to kidnap NPCs inside stores. This is achievable by driving a vehicle right at the entrance, cuffing that NPC, embark them and they will teleport to the car outside. This is difficult to stop them from getting kidnapped.

EDIT: Just realised that you don't even have to park right outside the shop's door, you can park anywhere near the shop and it'll still embark the NPC, unlike earlier versions of the game.

**Comment by UserR00T** [comment]
"Kidnapped npcs can free themselves and return after some time now,
I consider it fixed"  - NongBenz 2019
