### ISSUE TITLE
Problem online

### ISSUE THREAD

**Issue by SrHatter** [broke-protocol/BrokeProtocol#398]
For some days I have had a problem with the game. The problem started when it was free, then I decided to buy the game in steam to see if they fixed the problem but it continues.
My problem is that when I try to enter a server it returns me to the menu except in offline mode
also it happens to with all the servers even with versions 0.76

**Comment by DeathByKorea** [comment]
Make sure the game is allowed through windows firewall and that no antivirus is blocking it

**Comment by SrHatter** [comment]
I have already allowed it and no antivirus is blocking it

**Comment by SrHatter** [comment]
I have already allowed it and no antivirus is blocking it

**Comment by DeathByKorea** [comment]
Can you post the contents of `output.log` found in the game directory?

**Comment by SrHatter** [comment]
and where is that?
