### ISSUE TITLE
Basketballs don't spawn back

### ISSUE THREAD

**Issue by TheReaperG** [broke-protocol/BrokeProtocol#402]
If thrown somewhere else outside the jail, the basketballs doesn't spawn again. Not sure if this is just server issue, but can we have the basketballs spawn back every 5 minutes or so?

**Comment by UserR00T** [comment]
Are you sure about that? I did see them spawn back on 0.78a.

**Comment by UserR00T** [comment]
"Basket balls spawn correctly, the ones you steal and throw when outside are treated like other user-placed objects and will despawn after 24 hours."
