### ISSUE TITLE
Making/joining own server problem

### ISSUE THREAD

**Issue by Ghostduplicator7** [broke-protocol/BrokeProtocol#412]
So I was making my own server when I saw a problem on the BP-CM where I can't join but other people can, and the text is as follows: "Log: cannot connect after {3} attempt address {**_### My address_**}
Exception: Connection Error: 6
Unloading 2 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 139.835115 ms
Unloading 13 unused Assets to reduce memory usage. Loaded Objects now: 58481.
Total: 78.576719 ms (FindLiveObjects: 8.923960 ms CreateObjectMapping: 8.873365 ms MarkObjects: 59.666854 ms  DeleteObjects: 1.056444 ms)

**Comment by UserR00T** [comment]
I don't have any problems with it, probably related to your network.
