### ISSUE TITLE
Bug: Characters disappear when embarked to a despawned vehicle

### ISSUE THREAD

**Issue by cliff7422** [broke-protocol/BrokeProtocol#427]
1. Enter a vehicle, then get out in a location that causes the vehicle to despawn
2. Handcuff an NPC or player in the vicinity of the despawned vehicle
3. Embark the handcuffed character
4. Observe as the character will appear at the despawned vehicle's location for a second, then disappear.

I have no idea what happens to these characters when they disappear, but I assume they are teleported somewhere: maybe an empty map, maybe wherever the vehicle respawned at. Tested online, v0.85 hotfix.

**Comment by UserR00T** [comment]
Has been fixed, closing. Thank you for reporting this issue!
