### ISSUE TITLE
Bug: Glitching under the map

### ISSUE THREAD

**Issue by cliff7422** [broke-protocol/BrokeProtocol#429]
1. Find a suitable location: the glitch is performed in the water near any land. (Edit: probably not near the beaches, as the sloped land might make it too difficult to pass through.) For example, the outside edge of the military base.
2. While swimming in the water, face the wall and jump up and down while moving forward. Rapidly jumping is not effective, jump slowly and deliberately. I find that jumping at the lowest point in the water will give extra height to your jump, which in turn will sink you deeper into the water, allowing you to get under the geometry.
3. Once you get under the level, you can interact with some objects through the ground, such as the explosives safe in the military base. 

Tested online version 0.85 hotfix.

**Comment by UserR00T** [comment]
"This will always be an issue that the map creator should fix. Though on the default map it'll get fixed next update. Thank you for reporting this issue!"
