### ISSUE TITLE
BUG: Interpretations of the doubles in setting values and world builder

### ISSUE THREAD

**Issue by Tatitooo** [broke-protocol/BrokeProtocol#431]
Well there is a frightening mistake when editing a 'double' value, you can't put ',' and that doesn't let you put decimals in sound values or sensibility values, so if i wanna put 0,25 as a sensibility value, i can't because it only lets me put a '.', the 'Doubles' only interpret ',' as a separator between the whole number and the decimal.

**Comment by Tatitooo** [comment]
Well, testing a little bit it does change the thing, but the '.' itself doesn't stays if i close and reopen the settings menu

**Comment by UserR00T** [comment]
"Has been fixed, try to use '.' for decimal separators due to engine limitations however. Thank you for reporting this issue!"
