### ISSUE TITLE
Police car always de spawning 

### ISSUE THREAD

**Issue by ProgramRAM** [broke-protocol/BrokeProtocol#434]
#420 Every time I start up either a server or offline the moment I step out of the police car its over it just vanishes and as you can imagine that complicates being a police officer given transportation is impossible. Only other somewhat recent post I saw mentioning this was from back in 2018 so I thought I should bring this up to your attention. I have not joined any public servers only my own local and offline. Maybe I am doing it wrong? The steps I do are A get a drivers license B get the police job and C walk outside the police station and drive the police car. Should I be going somewhere else and buying a police car? All other vehicles seem to work fine only de spawning once I reach a fair distance and no one is in it. Running latest version on Steam. I have also tagged the related older issue.

**Comment by ProgramRAM** [comment]
#427 I just noticed there was a more recent issue post not sure if mine should be closed and merged.

**Comment by UserR00T** [comment]
From #420 "AI will clear empty cars from the road in front of them to prevent traffic jams on messy servers.
Not a bug, but could be better implemented, will a delay or something. For now, players should park their cars clear from traffic."
