### ISSUE TITLE
Server console

### ISSUE THREAD

**Issue by BrokeProtocol** [broke-protocol/BrokeProtocol#54]
The console will show all chat, and you will be able to issue commands directly to it.

**Comment by UserR00T** [comment]
[BP-ConsoleMonitor is the official logtail program for BrokeProtocol at the time being which tails the Player.log file.](https://github.com/UserR00T/BP-ConsoleMonitor)

**Comment by UserR00T** [comment]
Update: Broke Protocol v1.0 will have a dedicated console for I/O. [Read all about it here.](https://brokeprotocol.com/devlog-2-usability-back-end-progress/)
